version: '3.8'

name: 'maddevs'

services:
  grafana:
    image: grafana/grafana:9.5.6
    user: '0:0'
    env_file: ./config/env/.env
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./data/grafana:/var/lib/grafana
    networks:
      - internal
    ports:
      - '3000:3000'

  influx:
    image: influxdb:2.0
    env_file: ./config/env/.env
    volumes:
      - ./data/influx:/var/lib/influxdb2
    networks:
      - internal
    ports:
      - '8086:8086'
    healthcheck:
      test: curl -sL -I localhost:8086/ping | grep 204 || exit 1
      interval: 5s
      timeout: 10s
      retries: 100
  
  backend:
    build: ../src
    env_file: ./config/env/.env
    command: python3 main.py
    networks:
      - internal
    depends_on:
      influx:
        condition: service_healthy

networks:
  internal:
